# GEO settings for as-teh. The authoritative GEO policy is stored as LUA records in PostgreSQL.
# Location code: as-teh
geoip-database-files=mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
edns-subnet-processing=yes
