# GEO settings for us-nyc. The authoritative GEO policy is stored as LUA records in PostgreSQL.
# Location code: us-nyc
geoip-database-files=mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
edns-subnet-processing=yes
