# GEO settings for eu-ams. The authoritative GEO policy is stored as LUA records in PostgreSQL.
# Location code: eu-ams
geoip-database-files=mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
edns-subnet-processing=yes
